import { defineConfig } from 'tsup';

export default defineConfig([
  {
    entry: { 'core/index': 'packages/domain-c4/src/index.ts' },
    format: ['esm'],
    dts: true,
    sourcemap: true,
    clean: false,
    splitting: false,
    tsconfig: 'tsconfig.node.json',
    outDir: 'dist',
    target: 'es2022',
    platform: 'neutral',
    external: ['elkjs', 'zod', '@anthropic-ai/sdk', '@anthropic-ai/foundry-sdk', 'nanoid', 'fast-xml-parser'],
  },
  {
    // `cli/compute-worker`: el hilo de trabajo del cálculo de `iark serve` (`worker_threads`, ver src/cli/computePool.ts), que el CLI
    // localiza junto a sí (`dist/cli/compute-worker.js`). Va en esta misma configuración: comparte target, plataforma y externos.
    entry: { 'cli/index': 'src/cli/index.ts', 'cli/compute-worker': 'src/cli/computeWorker.ts' },
    format: ['esm'],
    dts: false,
    sourcemap: true,
    splitting: false,
    tsconfig: 'tsconfig.node.json',
    outDir: 'dist',
    target: 'node20',
    platform: 'node',
    banner: { js: '#!/usr/bin/env node' },
    external: ['elkjs', 'zod', '@anthropic-ai/sdk', '@anthropic-ai/foundry-sdk', 'commander', 'nanoid', 'fast-xml-parser', 'yaml'],
  },
  {
    entry: { 'embed/iark-module-element': 'src/embed/iark-module-element.ts' },
    format: ['esm', 'iife'],
    globalName: 'IArkModuleElement',
    dts: true,
    sourcemap: true,
    splitting: false,
    tsconfig: 'tsconfig.app.json',
    outDir: 'dist',
    target: 'es2020',
    platform: 'browser',
    minify: false,
  },
  {
    entry: { 'embed/iark-embed': 'src/embed/iark-embed.ts' },
    format: ['esm', 'iife'],
    globalName: 'IArkEmbed',
    dts: true,
    sourcemap: true,
    splitting: false,
    tsconfig: 'tsconfig.app.json',
    outDir: 'dist',
    target: 'es2020',
    platform: 'browser',
    minify: false,
  },
]);
